export const routes = {
  home: '/',
  collection: '/collections/:slug',
  product: '/product/:slug',
  search: '/search',
  wishlist: '/wishlist',
  cart: '/cart',
  checkout: '/checkout',
  about: '/about',
  contact: '/contact',
  shippingPolicy: '/shipping-policy',
  returns: '/returns',
  faq: '/faq',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  account: '/account',
  accountOrders: '/account/orders',
  accountOrderDetails: '/account/orders/:id',
  accountProfile: '/account/profile',
  accountAddresses: '/account/addresses',
}
